import streamlit as st
from PIL import Image
image = Image.open('kumtel.jpg')
header = st.container()
with header:
    st.title('welcome to the kumtel project')
    st.image(image)


options = st.multiselect(
     'Şuan çalışamayacak durumdaki makineler nelerdir?',
     ['press200-1', 'press160-1', 'press110-1', 'press60-1', 'press25-1', 'press500-1', 'press400-1', 'press160-2', 'press110-2', 'pressŞemmak'])
order_count =st.number_input('siparişte kaç farklı ürün var?',min_value=50,max_value=250,step=1)
order1=[0]*order_count
order2=[0]*order_count
    
for i in range(order_count):
    st.write(i+1,'. ürün özellikleri')
    order1[i]=st.selectbox('ürünün kodu ne?',key=i,options=['66 V.DİŞ PİPOLU L BORU 6 LI GALSİZ(13mm)', 'B66(ANK.MASTER)CAM KULPU BORU(470MM)KESİLMİŞ', 'BBQ TR CE BORU AYAK.54 CM.Ø16.0.8.KESİLMİŞ', 'LX-13620 EVA KULP BORUSU.324MM.Ø16.0.8.KESİLMİŞ', 'LX-3585 MASTER KULP BORUSU.359MM.Ø16.0.8.KESİLMİŞ', 'LX-411/412 GAZ DĞT.BORUSU (METAL CAM)GÖMME.', 'LX-7021 HOTPLATE KADEME BORUSU KES.Ø10*10 MM' 'LX-8520 EVA KULP BORUSU.240MM.Ø16.0.8.KESİLMİŞ (DELİK)', 'LX-8520 MASTER KULP BORUSU.252MM.Ø16.0.8.KESİLMİŞ (DELİK)', 'LX-8520 RUSTİK KULP BORUSU.253MM.Ø16.0.8.KESİLMİŞ', 'M6-40F 4 LÜ GAZ DĞT.BORUSU )GÖMME', 'TAM BOY FIRIN  L BORU.GAL.Lİ.5.Lİ.(ASYA)', 'TBF ARMUT SACI.(BÜKÜMLÜ)0,50', '60 KUM.PAN MERCURY(7 LI 2 SİN )İNOX BASKI', '60 KUM.PAN.ASYA MERCURY(6 Lİ 2 SİN)BASKISI', '60 KUM.PAN.ASYA MERCURY(7 Lİ 2 BUT 1 SİN)BASKISI', '60 KUM.PAN.ASYA MERCURY(7 Lİ 2 SİN)BASKISI', '66  ARKA PANEL SACI GAL.Lİ.TEK BACA', '66  KUM.PAN(6 LI 1ÇBUT 1SİN)PARLAK İNOX BASKISI', '66  KUM.PAN(6 Lİ 3 BUT)İNOX BASKISI', '66  KUM.PAN(7 LI 1ÇBUT 1SİN)PARLAK İNOX BASKISI', '66 DİNLENDİRME DIŞ KAPAĞI.SABİT.BASKISI.', '699 ISI PERDE ARA BÖLME SACI.GAL.Lİ', '699 ISI PERDE ARA BÖLME SACI.GAL.Lİ BACASIZ', '699 İÇ HAZNE ÖN SACI (MEGA)BASKI', '699 İÇ HAZNE ÖN SACI ELEKTRİKLİ BASKI', '699 ÖN ÇERÇEVE ALT  SACI BASKI', '70 LT FIRIN  KÖŞELİ TEPSİ BASKISI.', 'A6- GAZLI ANKASTRE ALÜZİ. BACA SACI', 'A6- GAZLI ANKASTRE ALÜZİ.BACA  AKTARMA SACI', 'A6- GAZLI ANKASTRE REFLEKTE ALM. PARLAK', 'A6 KUM.PAN GAL(2 Lİ DDT)GAZ İNOX BASKI LAZER', 'A6 KUM.PAN GALAXY CAM(2 Lİ  DT 1SİN 14 MM)BASKISI', 'A6 KUM.PAN GALAXY(2 Lİ DDT)GAZ İNOX BASKI.', 'A6 KUM.PAN GALAXY(3 LÜ 1 SİN POP-UP)BASKISI', 'A6 KUM.PAN GALAXY(3 LÜ 1 SİN)BASKISI.', 'A6 KUM.PAN GALAXY(3 LÜ 1 SİN)İNOX BASKI', 'A6 KUM.PAN GALAXY(3 LÜ 1 SİN)İNOX FİNGER.BASKI.', 'A6 KUM.PAN GALAXY(3 LÜ 1S POP-UP)İNOX BASKI.', 'A6 KUM.PAN GALAXY(3 LÜ 1S POP-UP)İNOX FİN.BASKI.', 'A6 KUM.PAN GALAXY(3 LÜ) DKP.', 'A6 KUM.PAN GALAXY(3 LÜ)BASKISI', 'A6 KUM.PAN GALAXY(3 LÜ)İNOX BASKI', 'A6 KUM.PAN GALAXY(3 LÜ)İNOX FİN.BASKI', 'ANKASTR OCAK MUS.TUTMA SACIÜSTTEN BAĞLAMALI GALSİZ', 'ANKASTRE FIRIN (I) SİDİNG SACI  İNOX  BASKI', 'ANKASTRE FIRIN SİDİNG(GİYDİRME) SACI  BASKI', 'ANKASTRE GİZLİ REZİSTANS SACI.GAL.Lİ.BASKI.', 'ANKASTRE SOĞUTMA FAN PERVANE SACI.GALLİ.', 'ATLANTİS ÖN KAPAK SAC PROFİLİ BASKISI', 'ATLANTİS ÖN KAPAK SAC PROFİLİ BASKISI VİDALI', 'ATLANTİS YAN ÇITA SAC PROFİLİ(SAĞ)BASKISI', 'ATLANTİS YAN ÇITA SAC PROFİLİ(SAĞ)BASKISI VİDALI', 'ATLANTİS YAN ÇITA SAC PROFİLİ(SOL)BASKISI', 'ATLANTİS YAN ÇITA SAC PROFİLİ(SOL)BASKISI.VİDALI', 'B66 ANK FIRIN FAN KORUMA SACI.GAL.Lİ.(0.50)', 'BBQ OUTDOOR TEPSİ.(ALÜMİNYUM NAYLONLU).', 'BBQ REZİSTANS.230V-1600W.İNDOOR.TR CE.PLK.ÇAKMA', 'BBQ REZİSTANS.230V-2200W.İNDOOR.TR CE.PLK.ÇAKMA', 'BBQ REZİSTANS.230V-2200W.OUTDOOR.TR CE.PLK.ÇAKMA', 'BBQ TR CE BORU AYAK BASKISI.54 CM.Ø16.0.8', 'BBQ TR CE REZİSTANS PLAKETİ.GAL.Lİ.BASKI', 'BBQ TR CE RÜZGARLIK SACI BASKISI.', 'BM BBQ REZİSTANS.230V-2200W.OUTD.PLK.ÇAKMA.YUV', 'CAM OCAK KÖPRÜ BAĞLAMA SACI GAL Lİ(24 MM)', 'CAM OCAK KÖPRÜ BAĞLAMA SACI(ORTA)GAL Lİ(21*30 MM)', 'CAM OCAK KÖPRÜ BAĞLAMA SACI(WOK)GAL Lİ(21*16 MM)', 'CAMLI OCAK EMN HVZ.BAĞ.SACI TRIBIL(LALE)BAS EMASİZ', 'CAMLI OCAK EMN HVZ.BAĞ.SACI WOK(LALE)BAS EMASİZ', 'CAMLI OCAK EMN HVZ.BAĞLAMA SACI WOK EMAYESİZ', 'CAMLI OCAK HVZ.EMNSİZ BAĞLAMA SACI 40 LIK  BASKI', 'CAMLI OCAK HVZ.EMNSİZ BAĞLAMA SACI 45 LİK BASKI', 'CAMLI OCAK HVZ.EMNSİZ BAĞLAMA SACI 50 LİK BASKI', 'KS-2710/2819 YANSITICI YAN DUVAR.ORTALI.UZUN ETEK', 'KS-2761/2861 REZİSTANS SABİTLEME SACI.GAL.BASKI', 'KS-2860 DERİN QUARTZ YANSITICI.PARLAK.NAY.2016', 'KS-2861 DERİN INFRARED YANSITICI.PARLAK.NAY.2016', 'KS-2861 REZİSTANS SABİTLEME SACI.BASKI.ALÜMİNYUM', 'KUMTEL FIRIN SÜS KAFESİ SABİTLEME SACI', 'LX 415-416 (YEKPARE)  DELİKLİ KÖŞE SACI', 'LX-8520 FIRIN ALÜMİNYUM YANSITICI.ALM.20 LİTRE', 'LX-8520 GÖVDE ARKA SACI.ALM.KAP.BASKI', 'LX-8520 GÖVDE ARKA SACI.BASKISI.PANJURLU.DKP', 'LX-8520 GÖVDE ARKA SACI.DKP.BASKI', 'LX-8520 GÖVDE ARKA SACI.GAL.Lİ.BASKI', 'LX-8520 HAZNE ARKA SACI.ALM.KAP.LI.BASKI', 'LX-8520 HAZNE ARKA SACI.BACASIZ.ALM.KAP.BASKI.', 'LX-8520 HAZNE ARKA SACI.GAL.Lİ.BASKI', 'LX-8520 IÇ HAZNE U SACI.ARMUT.GAL.Lİ.BASKI', 'LX-8520 IÇ HAZNE U SACI.M REZ.GAL.BASKI', 'T.B.F.DİNLENDİRME İÇ KAPAĞI.BASKISI', 'TAM BOY FIRIN FAN KORUMA SACI.DKP BASKI(0,60)', 'TAM BOY FIRIN FAN KORUMA SACI.DKP BASKI(0,60)', 'TAM BOY FIRIN İÇ HAZNE REZİ.KAPAĞ(0,40)', 'TAM BOY FIRIN İÇ HAZNE REZİSTANS KAPAĞI.', 'TAM BOY FIRIN İÇ HAZNE REZİSTANS KAPAĞI.GAZ. TEMPAR', 'TAM BOY FIRIN ŞİŞ KARŞILAMA SACI GAL.KAP', 'TBF ANKASTRE ALT SACI BASKI', 'TLF-69 MOTOR BAĞLAMA SACI.GAL.Lİ.BASKI', 'TLF-69 MUSLUK BAĞLAMA KELEPÇESİ 6 LI.GAL.Lİ', 'TLF-69 MUSLUK BAĞLAMA KELEPÇESİ 7 Lİ.GAL.Lİ', 'TLF-69.KUM.PAN İÇ SACI(6M 3R)BASKI', 'TLF-69.KUM.PAN İÇ SACI(7M +1 3 BUT)BASKI (LAZER)'])
    order2[i]=st.slider('üründen kaç adet sipariş geldi?',key=i,min_value=5,max_value=100,step=1)
    

st.button('çalıştır')

    
    
st.subheader('Planalama yapılırken biraz müzik dinlemek ister misiniz ?')
audio_file = open('erik.ogg', 'rb')
audio_bytes = audio_file.read()
st.audio(audio_bytes, format='audio/ogg')
        